export const mockScripts = [
  {
    id: "vehicle-studio",
    name: "Vehicle Studio",
    price: "R$104",
    priceNum: 104,
    image: "https://images.unsplash.com/photo-1519440862171-af26cf8c2a85?w=600&h=400&fit=crop&auto=format",
    cardGradient: "linear-gradient(135deg, #7c2d00 0%, #c2410c 50%, #f97316 100%)",
    category: "Vehicles",
    description:
      "IO Vehicle Studio is an all-in-one advanced vehicle photography tool for FiveM built to quickly generate hundreds of high-resolution vehicle images with transparent backgrounds for IO Advanced Garages, IO Dealerships and any other script that needs vehicle images. Spawn styled showcased shots or add vehicle parts, position and save.",
    features: [
      "AI Fast Bulk Vehicle Imaging: Create hundreds of high-resolution vehicle images in minutes, with clean transparent background ready for your other scripts.",
      "Transparent Backgrounds: Vehicle Studio will automatically remove the background and render your vehicle making minimal editing.",
      "Built for IO Scripts: Perfect for creating thumbnails for IO Advanced Garages, IO Dealerships, HUD, and any other vehicle photos.",
      "Built-In Keyword Images: Save a store listing for matching product images. Get the perfect shot of your vehicles settings or advertise vehicle showcase.",
    ],
    tags: ["Vehicles", "Photography", "UI"],
  },
  {
    id: "mechanic",
    name: "Mechanic",
    price: "R$50",
    priceNum: 50,
    image: "https://images.unsplash.com/photo-1611760357505-922600d8ffa6?w=600&h=400&fit=crop&auto=format",
    cardGradient: "linear-gradient(135deg, #14532d 0%, #16a34a 50%, #4ade80 100%)",
    category: "Jobs",
    description:
      "A fully featured Mechanic job script for FiveM. Includes repair stations, job ranks, mechanic zones, and a full parts inventory system. Highly configurable and compatible with most frameworks including ESX and QBCore.",
    features: [
      "Multi-Framework: Compatible with ESX and QBCore out of the box.",
      "Repair Zones: Configurable repair locations with optional animations.",
      "Parts System: Full inventory integration for mechanic parts and tools.",
      "Job Ranks: Customizable rank system with pay scales and permissions.",
    ],
    tags: ["Jobs", "ESX", "QBCore"],
  },
  {
    id: "dealerships-v2",
    name: "Dealerships v2",
    price: "R$321",
    priceNum: 321,
    badge: "v2",
    image: "https://images.unsplash.com/photo-1650486175161-fcfaf1d83c81?w=600&h=400&fit=crop&auto=format",
    cardGradient: "linear-gradient(135deg, #1e1b4b 0%, #4338ca 50%, #818cf8 100%)",
    category: "Vehicles",
    description:
      "The most comprehensive vehicle dealership system for FiveM. Features a beautiful 3D vehicle preview system, test drives, financing options, and full administrative management. Compatible with most economy frameworks.",
    features: [
      "3D Previews: Full in-game 3D vehicle showcasing with real-time color and mod selection.",
      "Finance System: Built-in financing with configurable interest rates and payment schedules.",
      "Test Drives: Allow players to test vehicles before purchasing.",
      "Admin Panel: In-game admin panel for managing stock, pricing and vehicle categories.",
    ],
    tags: ["Vehicles", "Economy", "ESX"],
  },
  {
    id: "advanced-garages-v3",
    name: "Advanced Garages v3",
    price: "KB?",
    priceNum: 0,
    badge: "v3",
    image: "https://images.unsplash.com/photo-1622836270623-0a8072ed6eec?w=600&h=400&fit=crop&auto=format",
    cardGradient: "linear-gradient(135deg, #7f1d1d 0%, #dc2626 50%, #f87171 100%)",
    category: "Vehicles",
    description:
      "Advanced Garages v3 is the ultimate vehicle storage system for FiveM servers. With beautiful image thumbnails powered by IO Vehicle Studio, players can easily browse and retrieve their owned vehicles. Supports shared garages, impound lots, and job-restricted access.",
    features: [
      "Image Thumbnails: Displays auto-generated vehicle images via IO Vehicle Studio.",
      "Shared Garages: Allow players to share garage access with partners or crews.",
      "Impound System: Automatic impound with configurable fine and retrieval system.",
      "Job Garages: Restrict garage access by job, rank or gang membership.",
    ],
    tags: ["Vehicles", "Storage", "ESX"],
  },
  {
    id: "hud",
    name: "HUD",
    price: "KB71",
    priceNum: 71,
    image: "https://images.unsplash.com/photo-1610913721979-b20ede600e63?w=600&h=400&fit=crop&auto=format",
    cardGradient: "linear-gradient(135deg, #0c4a6e 0%, #0284c7 50%, #38bdf8 100%)",
    category: "UI",
    description:
      "A premium HUD system for FiveM with clean design and full customization. Displays health, armour, hunger, thirst, money, stress, and vehicle speed with smooth animations. Fully configurable and optimized with near-zero resource usage.",
    features: [
      "Performance Optimized: Near-zero resource usage, tested on 200+ player servers.",
      "Fully Configurable: Adjust every element position, size, and color.",
      "Vehicle Speedometer: Shows speed, fuel, gear and engine state.",
      "Status Bars: Health, armour, hunger, thirst, and stress with animated transitions.",
    ],
    tags: ["UI", "HUD", "All Frameworks"],
  },
  {
    id: "handling-pro",
    name: "Handling Pro",
    price: "KB40",
    priceNum: 40,
    image: "https://images.unsplash.com/photo-1619262105903-c65a6396c72f?w=600&h=400&fit=crop&auto=format",
    cardGradient: "linear-gradient(135deg, #312e81 0%, #7c3aed 50%, #c084fc 100%)",
    category: "Vehicles",
    description:
      "Handling Pro gives players and admins the ability to fine-tune every vehicle handling parameter in real time. Includes save/load presets, permission-based access, and a clean NUI interface. Great for drag racing servers or realistic handling mods.",
    features: [
      "Real-Time Editing: Modify handling values live without restarting.",
      "Preset System: Save and share handling configurations.",
      "Permission Control: Restrict access by admin rank, job or ACE permissions.",
      "Handling Library: Comes preloaded with tuned handling profiles for popular vehicles.",
    ],
    tags: ["Vehicles", "Admin", "ESX"],
  },
];
